name: florea
description: Florea - Balance Your Mind, Study & Life.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  supabase_flutter: ^2.8.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  intl: ^0.20.3
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  form_builder_validators: ^11.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
